Add unit tests
waggle-sensor/beekeeper-manifest pull request #16
Opened 2022-11-17 16:39 UTC by iperezx

- Adds simple unit tests
- Fixes tag data model to be able to test it.

2022-11-17 16:40 UTC, iperezx commented
The fix on the tag data model is needed for the stuff I am working on with the fixtures.

2022-11-17 20:03 UTC, seanshahkarami requested changes
This looks pretty good. Can you all add a unit test which exercises the public API? Then we can call this done.

2022-11-17 20:03 UTC, seanshahkarami commented on api/ManifestApp/tests.py
> +        self.assertEqual(N.computes.count(), 1)
This is a good start.

Can we extend this with a test that exercises the public API? Something like:

```python
    def test_get_manifest(self):
        r = self.client.get("/ManifestApp/api/nodes/A/")
        self.assertEqual(r.status_code, 200)
        data = r.json()
        # check that data matches expected manifest format for this node and includes any repopulated compute, hardware, etc.
```

2022-11-21 21:46 UTC, seanshahkarami approved these changes

2022-11-21 21:49 UTC, merged